### ISSUE TITLE
(No issue, didnt know where else to comment) Amazing app! The fastest downloader I have ever used BY FAR! Thank you good sir!

### ISSUE THREAD

**Issue by via80HD** [Markkop/yt-dlandcut#17]
I apologize for putting this in the issues section I am new to GitHub and I just didnt know where else to say thank you for this amazing app. The shit is fast as fuck and easy to use AND barely takes up any space on my shitty no memory havin ass laptop! 

Thanks again 

![image](https://user-images.githubusercontent.com/84550322/125965621-2e37e4aa-0a2f-45a6-97fb-ed3b607779c9.png)

**Comment by Markkop** [comment]
Oh, hey!
Thanks!
I'm kinda impressed that people are actually using it and without any problems.
I hope to get time to improve it someday :D

**Comment by via80HD** [comment]
> 
> 
> Oh, hey!
> Thanks!
> I'm kinda impressed that people are actually using it and without any problems.
> I hope to get time to improve it someday :D

It did work really well for a while then all of a sudden it wouldn't work anymore, I cant remember what the issue was but still when it was working it was super fast. lol
